### ISSUE TITLE
Help Offered

### ISSUE THREAD

**Issue by hypnot0ad** [dlenski/network-manager-openconnect#2]
This seems to be the only implementation of Global Protect that works on Linux using the GP native protocol and not vpnc, and for that, thank you!

I currently use your implementation running a bash script and it works fine, although probably not installed properly. Integration with Network Manager would be awesome too, although I'm not smart enough to build it without instruction ;)

Given this is the only working implementation, I would like to assist, to make it better by helping out with some how-to's or install instructions. But in order to do this, I need a working install myself ;) Chicken, meet Egg...

Is there any relevant info you have come across, not necessarily GP, that I could use to hack together some doco for you? Perhaps a basic build openconnect from source that references correct directories etc, then I can work from there.

Hope I can be of assistance.

**Comment by dlenski** [comment]
Hi @hypnot0ad, thanks for the kind words! You're trying to build the NM plugin under Linux, right?

Building the plugin *is* somewhat harder to build and debug than the command-line openconnect client. (Personally, I don't use the NM plugin because I greatly prefer the scriptability and flexibility of the CLI.)

The changes in this repository have already been merged into the official Gnome repository (see [commit 1ed6de801](https://git.gnome.org/browse/network-manager-openconnect/commit/?id=1ed6de801a398887277fbb9c35d9f5f5d6c4d5c3)) so they will be included in the next official release.

Quite honestly, if the command-line version is working for you, it's probably best just to wait for the next release of the NM plugin :smile:

If you want to contribute to the overall reliability of the GlobalProtect support, and know how to build and debug the command-line client, what I most need help with is [writing a script to handle the HIP "host intrusion protection" support](https://github.com/dlenski/openconnect/issues/36) since that appears to be the major remaining obstacle to successful connection for many users.

**Comment by Zjemm** [comment]
Do you mean that the GP option schould appear when installing the official networkmanager-openconnect plugin? Because i just installed your version but the GP option does not appear in the network-manager

it installed fine an the CLI openconnect version works great with GP, but unfortunaltly in NM it does not show. probably missing something

**Comment by dlenski** [comment]
> Do you mean that the GP option schould appear when installing the official networkmanager-openconnect plugin? Because i just installed your version but the GP option does not appear in the network-manager

No. Unless you are building the `networkmanager-openconnect` plugin **from the source code in this repository** and **also building `libopenconnect` from dlenski/openconnect**, you will not get the GP options in the plugin.

The changes in this repository were merged into the official NM plugin in May (https://git.gnome.org/browse/network-manager-openconnect/commit/?id=1ed6de801a398887277fbb9c35d9f5f5d6c4d5c3) but:

a. these changes haven't been included in a release yet
b. the NM-plugin changes don't do anything by themselves without a compatible `libopenconnect`  including GP support

**Comment by Zjemm** [comment]
ahh, that explains  thnx :)
